import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/legal-shared";

export const metadata: Metadata = {
  title: "Terms of Service — LRS™",
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <LegalLayout
      backHref="/vente"
      backLabel="← Back to LRS™"
      title="Terms of Service"
      updatedLabel="Last updated: to be filled in before publishing"
      noticeLabel="Template — needs review."
      notice="A reasonable starting point, not legal advice — have it
        validated by a professional before going live, especially the
        liability and termination clauses."
    >
      <LegalSection heading="1. Purpose">
        <p>
          LRS™ (&quot;the Service&quot;) is a landing page and ad audit tool
          that scores a page or ad copy (hook, offer, trust, friction) and
          provides recommendations, before you launch a paid campaign.
        </p>
      </LegalSection>

      <LegalSection heading="2. Subscription">
        <p>
          Access to the Service requires a paid subscription, billed monthly
          via Stripe. The subscription renews automatically until cancelled.
          Cancellation takes effect at the end of the current billing
          period; no prorated refund is issued unless stated otherwise.
        </p>
      </LegalSection>

      <LegalSection heading="3. Permitted use">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            You are responsible for the content you submit to the Service
            (URLs, ad copy).
          </li>
          <li>
            You will not submit illegal content, content belonging to a
            third party without authorization, or attempt to disrupt or
            bypass the Service&apos;s security.
          </li>
          <li>
            The account is personal — sharing a paid access with
            unauthorized third parties is not permitted.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="4. Nature of the service — limitation of liability">
        <p>
          The scores and recommendations generated by LRS™ are produced by
          an AI model and provided for informational purposes only. They do
          not constitute a guarantee of advertising performance nor
          professional (marketing, legal, or other) advice. You remain
          solely responsible for decisions made based on these
          recommendations.
        </p>
      </LegalSection>

      <LegalSection heading="5. Availability">
        <p>
          The Service is provided &quot;as is&quot;. We strive for
          reasonable availability but do not guarantee uninterrupted or
          error-free operation.
        </p>
      </LegalSection>

      <LegalSection heading="6. Termination">
        <p>
          You may cancel your subscription at any time. We may suspend or
          terminate access in the event of a clear violation of these
          terms.
        </p>
      </LegalSection>

      <LegalSection heading="7. Contact">
        <p>For any question about these terms: [contact email].</p>
      </LegalSection>
    </LegalLayout>
  );
}
